server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址 需启动一个单体的nacos服务
    gateway:
      routes:
        - id: user-service # 路由id，自定义，只需要唯一即可
          uri: lb://user-service # 路由的目标地址，lb表示负载均衡，后面跟服务名称
          # uri: http://localhost:8081 # 路由的目标地址，http就是固定地址,一般使用上面那种
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要是以/user开头的，就符合规则

          filters:
            - AddRequestHeader=any, Welcome to chinzicam's Blog! # 添加请求头,这里的any是请求参数
#      default-filters:  # 全局过滤器
#        - AddRequestHeader=Truth, Welcome to chinzicam's Blog! # 添加请求头

        - id: order-service # 按照上面的写法，再配置一下order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:9527"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期